# Generated by Django 5.1.7 on 2025-04-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('maintenance', 'صيانة'), ('utilities', 'مرافق'), ('security', 'أمن'), ('cleaning', 'تنظيف'), ('other', 'أخرى')], max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.apartment')),
            ],
        ),
    ]
